---

sudo: false

language: python

matrix:
  fast_finish: true
  include:
    - env: BUILD=test
      python: '2.7'
    - env: BUILD=test
      python: '3.3'
    - env: BUILD=test
      python: '3.4'
    - env: BUILD=test
      python: '3.5'
    - env: BUILD=test
      python: '3.6'
    - env: BUILD=test
      python: '3.7'
      dist: xenial
    - env: BUILD=test
      python: 'pypy'

    - env: BUILD=docs
      python: '3.6'

install:
  - pip install -r requirements/dev.txt

script:
  - |
    set -ex
    case "$BUILD" in
      test)
        nosetests --with-coverage --cover-package=asciimatics
        ;;
      docs)
        cd doc && cp source/conf_orig.py source/conf.py && ./build.sh
        ;;
    esac
    set +ex

after_success:
  - |
    set -ex
    case "$BUILD" in
      test)
        ;;
    esac
    set +ex
